export default {
  EVENT_VIEW_PROFILE: "EVENT_VIEW_PROFILE",
  OPEN_PAYMENT_MODAL: "OPEN_PAYMENT_MODAL",
  EVENT_VIEW_ARTICLE: "EVENT_VIEW_ARTICLE",
  OPEN_FILTER_PANEL: "OPEN_FILTER_PANEL",
  OPEN_MEMBER_PANEL: "OPEN_MEMBER_PANEL",
  MEMBER_CHANGED: "MEMBER_CHANGED",
  EVENT_CHANGED: "EVENT_CHANGED",
  OPEN_ATTENDANCE_DISCLAIMER: "OPEN_ATTENDANCE_DISCLAIMER",
  VISIT_CERTIFICATE_PAGE: "VISIT_CERTIFICATE_PAGE",
};
