export default {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  LEARNING_LIBRARY: "/learning-library",
  MENTORING: "/mentoring",
  EVENTS: "/events",
  CERTIFICATIONS: "/certifications",
  HUB: "/hub",
  FAVORITES: "/favorites",
  READ_LATER: "/read-later",
  ARTICLE: "/article",
  CERTIFICATE: "/certificate",
  HEART: "/heart",
};
