export default {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PASSWORD_RECOVERY: "/password-recovery",
  RESET_PASSWORD: "/reset-password/:token",
  LEARNING_LIBRARY: "/learning-library",
  MENTORING: "/mentoring",
  EVENTS: "/events",
  CERTIFICATIONS: "/certifications",
  HUB: "/hub",
  FAVORITES: "/favorites",
  READ_LATER: "/read-later",
  ARTICLE: "/article",
  CERTIFICATE: "/certificate",
  HEART: "/heart",
  PODCAST: "/podcast",
  PUBLIC_EVENT: "",
  JOIN: "/join",
  TERMSOFUSE: "/terms-of-use",
  MARKETPLACE: "/marketplace",
  PUBLIC_MARKETPLACE: "/public-marketplace",
  CONFERENCE_LIBRARY: "/conference-library",
  NOT_FOUND: "/not-found",
};
