export default {
  NEW_EVENT: "new-event",
  LIVE_CHANGE: "live-change",
  SEND_MESSAGE_GLOBAL_CONFERENCE: "SEND_MESSAGE_GLOBAL_CONFERENCE",
  USER_ONLINE: "USER_ONLINE",
  USER_OFFLINE: "USER_OFFLINE",
  MESSAGE: "MESSAGE",
  SEND_MESSAGE: "SEND_MESSAGE",
};
